- Week 1/BOJ_실버 3_먹을 것인가 먹힐 것인가/hyungjoon.py
- Week 1/BOJ_실버 3_블로그/hyungjoon_failed.py
- Week 1/BOJ_실버 3_블로그/hyungjoon_solved.py
- Week 2/BOJ_실버 2_랜선 자르기/hyungjoon_solved.py
[먹을 것인가 먹힐 것인가](https://www.acmicpc.net/problem/7795)
소요 시간 : 30분  
- 이분탐색 기본문제입니다. 이분탐색을 안푼지가 오래되서 너무 오래걸렸습니다..
[블로그](https://www.acmicpc.net/problem/21921)
소요 시간 : 40분  
- 투포인터 문제라고 해서 투포인터나 이분탐색으로 접근했는데, 누적합과 슬라이딩 윈도우로 풀 수 있었습니다.
- 누적합 풀이는 실패해서 슬라이딩 윈도우로 풀이했습니다.
[랜선 자르기](https://www.acmicpc.net/problem/1654)
소요 시간 : 20분  
- 랜선을 기준으로 이분탐색을 진행했습니다. 특별히 어려운 점은 없었습니다.
> [Solve] 저번주문제 + 이번주 월요일 문제

- Week 2/BOJ_실버 1_기타 레슨/hyungjoon.java
[기타 레슨](https://www.acmicpc.net/problem/2343)
소요 시간 : 1시간 20분
- 어떻게 풀지 계속 고민하다 결국 답지를 봤습니다.
- 문제 이해하는데 너무 오래걸렸습니다. 모든 블루레이의 길이가 17로 동일해야한다는 건줄알았어요..
> [Sovled] BOJ_2343_기타 레슨

- Week 2/BOJ_실버 3_IF문 좀 대신 써줘/sohyeon.java
[if](https://www.acmicpc.net/problem/19637)
소요 시간 : 1시간
출력은 스빌 출력은 스빌 출력은 스빌 출력은 스빌 출력은 스빌 출력은 스빌
별생각없이 처음에는 트리맵써서 해결하려고 했는데 시간 복잡도를 계산하고 어떤 알고리즘을 적용해여할지 고민하는 시간을 가지는 습관을 들여야겠습니다
> [Solved] BOJ_19637_실버3_IF문 좀 대신 써줘

- Week 3/BOJ_실버4_수들의 합 2/hyungjoon_failed.java
- Week 3/BOJ_실버4_수들의 합 2/hyungjoon_solved.java
[수들의 합2](https://www.acmicpc.net/problem/2003)
소요 시간 : 35분  
- 처음엔 누적합으로 풀려다가 투포인터로 전환함
- 0과 1에서 출발하는 l, r 포인터를 두고, 조건에 따라 + 해줬습니다.
- 합이 m보다 적을때도 r++ 해줬어야 했는데 이 부분을 캐치를 못해서 오래걸렸습니다.
- 누적합 풀이가 분명 있을 것 같은데, 잘 안풀림... 내일 다시 해보겠읍니다.
> [Solved] BOJ_2003_수들의 합2

- Week 3/BOJ_실버1_귀여운 라이언/hyungjoon_failed.py
- Week 3/BOJ_실버1_귀여운 라이언/hyungjoon_failed2.py
[귀여운 라이언](https://www.acmicpc.net/problem/15565)
소요 시간 : 100분
- 100분의 사투끝에 결국 답지를 봤음
- 투포인터의 특성을 제대로 이해하지 못한 상태에서 접근했기 때문에 오래걸렸음. l 포인터를 움직이긴 하는데, 접근법이 잘못됐었다.
- cnt를 기준으로 분기처리를 했어야 했는데.. arr[r] 을 기준으로 분기처리를 했기 때문에 자꾸 틀렸었음
- 첫 풀이는 두 번째로 만나는 라이언을 next_l 로 두고, 한번의 투포인터 탐색이 끝나면 l 포인터를 next_l로 갱신시켜 다시 투포인터 탐색을 진행하면서 값을 갱신하는 방법으로 진행했습니다.
하지만 시초 발생...
- 이 문제를 해결하려고했는데 끝내 해결을 못하고 답지를 봤습니다. 뭔가 단순한 문제같은데 왜케 안풀리는지..ㅠㅠ
> [Failed] BOJ_15565_귀여운 라이언

- Week 3/BOJ_실버1_귀여운 라이언/Jongmin.java
- Week 3/BOJ_실버1_귀여운 라이언/hyungjoon_failed.py
- Week 3/BOJ_실버1_귀여운 라이언/hyungjoon_failed2.py
- Week 3/BOJ_실버2_나무 자르기/Jongmin_fail.java
[귀여운 라이언](https://www.acmicpc.net/problem/15565)
소요 시간 : 2시간?  
- 알고보니 이번 주는 슬라이딩 윈도우? 투포인터? 구간이었나봐요 풀이가 비슷한 것 같습니다
- head와 tail 이 각각 움직이고 최악의 상황에서 둘 다 리스트를 한 번 순회하니 $O(N)$ 인 것 같습니다.
- 풀이법은 비슷하였으나 인덱스 처리를 제대로 못해서 OutOfBound가 일어나서 처리하느라 애먹었습니다.
알고리즘 책 하나 사서 공부하는거 도움 될까요? 혹시 추천해주실 책 있나요? 
[나무자르기](https://www.acmicpc.net/problem/2805)
소요 시간 : n시간  
- 처음 생각한 풀이 방법은 먼저 정렬을 한 후 최대높이 -1 부터 총 길이가 $K$ 이하일때까지 각 높이별로 계산을 합니다 
-정렬  $O(nlogn)$ + 총 높이 계산 $O(N)$  정도로 생각했으나 생각보다 깔끔한 구현을 생각하지 못해 형준님 힌트를 바탕으로 다른 방법을 생각했습니다. ( 시간이 남으면 첫 번째로 생각한 방식도 구현 예정)  
- 최대 높이와 최저 높이를 설정한 후 그 중간 높이로 잘랐을 경우 잘린 나무의 길이의 총 합이$K$ 보다 큰지 작은지 판단합니다.
- 크면 mid 이상의 높이에서 그보다 더 K값에 근접한 값을 찾기 위해 최저 높이를 높입니다. 
- 반대로 부족하면 mid 이상의 높이로 자르면 $K$값 이상을 구할 수 없으므로 최대 높이를 낮춥니다 
- 이런식으로 최적 높이를 구하여 결과를 반환합니다
실패한 이유
- 모르겠습니다. 백준 36%에서 계속 답이 틀렸다고 …
> [Solved] BOJ_15565 귀여운 라이언, [Failed] BOJ_2805 나무자르기

- Week 3/BOJ_골드5_수 고르기/hyungjoon_failed.py
- Week 3/BOJ_골드5_수 고르기/hyungjoon_failed2.py
- Week 3/BOJ_골드5_수 고르기/hyungjoon_solved.py
- Week 3/BOJ_실버2_나무 자르기/hyungjoon_failed1.java
- Week 3/BOJ_실버2_나무 자르기/hyungjoon_failed2.java
- Week 3/BOJ_실버2_나무 자르기/hyungjoon_failed3.java
- Week 3/BOJ_실버2_나무 자르기/hyungjoon_optimized.java
- Week 3/BOJ_실버2_나무 자르기/hyungjoon_solved.java
[나무 자르기](https://www.acmicpc.net/problem/2805)
소요 시간 : 80분  
- 결론부터 말하자면 temp 값을 int로 둬서 삽질을 겁나 했음. long으로 뒀어야 했다.
- 나무의 arr를 기준으로 l과 r포인터를 잡는게 아닌, 높이를 기준으로 l과 r포인터를 잡았다.
1차 시도
- 사실 이 때 다 푼거였음. temp값이 int여서 답이 틀렸다. 왜 틀렸는지 찾아봤음.
2차 시도
- mid값이 잘못된건가 해서 answer를 빼고 mid를 조정하면서 정답을 answer를 안넣고 답을 도출해봤음.
3차 시도
- 이번엔 시초 발생, 처음에 arr를 입력하고, 그 다음에 max값을 구할 때 또 arr를 돌아서 총 O(2N)의 시간복잡도가 걸림.
- 이게 문제인가 싶어서 arr를 만들어줌과 동시에 max값을 구하도록 로직을 바꿔봤음, 그래도 답이 오답
4차 시도
- 결국 답을 봤음. 답을 봤는데도 한참동안 왜 내 답이 안되는지 몰랐었는데, long 때문이었음. 얘 하나만 고치니까 원래 답이 맞았음.
5차 시도
- 정답 최적화 진행, stream을 두번 썼을 때보다 150ms 가량 줄어들었음.
[수 고르기](https://www.acmicpc.net/problem/2230)
소요 시간 : 45분
- 어제 문제도 그렇고 범위로 아주 농락당한 기분임..
- 문제에서 "이 수열에서 두 수를 골랐을 때(같은 수일 수도 있다)" 조건이, 인덱스는 다른 같은 수라는 줄 알고 l과 r을 0과 1로 두고 시작했음.. 이게 주 오답 요인이었음.
1차 시도
- 투포인터 로직 자체는 같지만, 시작점을 …
> [Failed] BOJ_실버2_나무 자르기, [Solved] BOJ_골드5_수 고르기

- Week 3/BOJ_골드5_수 고르기/Jongmin.java
[수 고르기](https://www.acmicpc.net/problem/2230)
소요 시간 : 50분  
- 처음에는 정렬하지 않고 head와 tail만 움직였다가 이렇게 풀다가는 모든 경우를 다 비교해야 하기 때문에 $O(N^2)$ 인데다가 비교가 누락된다는 사실을 파악했습니다.
- 후에는 오름차순으로 정렬한 후 $O(NlogN)$ head와 tail이 움직여서 그 차를 구하므로 $O(N+N) = O(N)$, $O(N)+O(NlogN) = O(NlogN)$ 의 시간복잡도(맞나요?) 정도의 시간으로 풀 수 있을 거라고 판단했습니다. 
제가 진자 풀때는 아까 형준님 코드 리뷰한거 생각 안났거든요? 이 경우 solved인가요 failed인가요
> [Solved] BOJ 2230 수 고르기

- Week 4/BOJ_실버3_시리얼 번호/sohyeon_solved.java
[시리얼 번호](https://www.acmicpc.net/problem/1431)
소요 시간 : 30분  
- 정렬 문제 풀었습니다. 크게 어려운 문제는 아니었던 것 같아요. 그런데 그냥 빨리 푼다고 클래스의 필드를 public으로 열어두고 썼는데, 알고리즘에서도 이런 캡슐화를 신경쓰면서 푸는게 좋을까요?
- Arrays.sort 내부를 좀 뜯어보려구요!
> [Solved] BOJ_1431_실버3_시리얼번호

- Week 4/BOJ_실버3_시리얼 번호/hyungjoon_failed.java
[시리얼 번호](https://www.acmicpc.net/problem/1431)
소요 시간 : 70분  
- 자바에서 정렬하는 법을 잘 모르겠어서 검색을 좀 했습니다.
- 오늘 문제는 특별히 로직이 있다기보단 정렬 구현이라.. 크게 문제될 건 없는듯 합니다.
- 36, 41번 라인에서 왜 상수로 때려버리면 오답인지를 잘 모르겠습니다. 제발 답변좀..!!!
> [Failed] BOJ_실버3_시리얼 번호

- Week 4/BOJ_실버3_시리얼 번호/Jongmin_success.java
61번 라인의 char를 String으로 변환하는 부분은 인터넷을 참고했습니다.
[시리얼 넘버](https://www.acmicpc.net/problem/1431)
소요 시간 : 60분  
자바의 Arrays.sort를 활용하기 위해 기타 객체를 만들고 comparable 인터페이스를 상속하여 비교 함수 부분만 문제의 의도대로 만들었습니다.
Arrays.sort를 쓰지 않고 정렬 함수를 따로 구현해야하는지 궁금했지만, 오늘은 시간이 부족해서 이렇게 했습니다.
Array.sort 의 내부를 보지 않아서 정렬 방식을 모르겠지만 아마도 $O(NlogN)$ 일 것 같습니다. 
이번 주내내 정렬문제니... 언어의 기본 정렬 함수 써도 괜찮나요? 아니면 되도록 따로 만드는게 좋을까요?
> [Solved] BOJ 1431 시리얼넘버

- Week 4/PRG_레벨2_요격 시스템/hyungjoon_solved.java
- Week 4/PRG_레벨2_요격 시스템/hyungjoon_solved.py
- Week 4/PRG_레벨2_요격 시스템/hyungjoon_test.java
[요격 시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
소요 시간 : 12분
- 끝나는 지점을 기준으로 오름차순 정렬하는 것이 핵심
- 기존에 발사한 요격 미사일로 날아오는 미사일을 요격할 수 없다면, 하나 추가해주고 해당 요격 미사일의 발사지점을 이동해주는 것이 포인트
- 사실 전 이전에 푼 문제였는데 복습하고자 했습니다.. 하핫
- 자바 정렬은 정말 외워지지가 않네요..ㅠㅠ
이전에 Arrays.sort()와 Collections.sort()가 생각나서, Collections.sort()로도 해당 문제를 풀어봤습니다.
(hyungjoon_test.java 참고)
Collections.sort() 사용
Arrays.sort() 사용
의외로 Collections.sort()가 느린걸로 나왔는데요, 아무래도 List로 전환하는 과정이 추가되었기 떄문이지 않나 싶습니다.
그러니까, 애초에 List로 만들 수 있는 환경이면 Collections.sort() 를 쓰고, 매개변수가 배열로 넘어와서 배열로 써야되는 상황에선 Arrays.sort()를 쓰는 것이 타이핑 시간줄이기도 용이하고 실행시간도 절약되는 듯 합니다.
사실 Arrays.sort()썼냐 Collections.sort()썼냐로 시초가 나는 문제는 아직까진 보지 못했습니다..;
> [Solved] PRG_레벨2_요격 시스템

- Week 4/PRG_레벨2_요격 시스템/sohyeon.java
[요격 시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
소요 시간 : 1일  
- 정말 띠용스러운데 요격 받는 쪽과 요격하는 쪽을 헷갈려서 문제를 못 풀던거였습니다.... 어쩐지... 어디를 방어해야할지 좌표도 안주고서 어딜 막으라는 건지.......라고 고민했네요......
> [Failed] PG_레벨2_요격 시스템

- Week 4/PRG_레벨1_문자열 내 마음대로 저장하기/sohyeon.java
[내맘대로 문자열 정렬하기]()
소요 시간 : 30분  
- 원하는 인덱스를 일순위 기준으로하여 문자열을 검색하고 다음 기준으로는 그냥 알파벳 순으로 정렬하는 문제였습니다. 
앞에서 풀었던 문제처럼 단어에 대한 클래스를 정의하고 그 클래스에 string과 기준이 되는 index를 담아두도록 했는데 이유는  오버라이딩할 정렬함수에 index를 어떻게 전해줄지 고민하다가 그냥 객체에 가지고 있는 this.를 사용하게 했기 때문입니다. 
하지만 이러면 같은 index 값을 모든 Word 클래스에서 가지고 있게 되기 때문에 별로 좋은 방법 같지는 않네요ㅠㅠ
> [Solved] PRG_레벨1_문자열 내 마음대로 저장하기  

- Week 5/BOJ_실버2_222-풀링/hyungjoon_failed.java
- Week 5/BOJ_실버2_222-풀링/hyungjoon_optimized.java
- Week 5/BOJ_실버2_222-풀링/hyungjoon_solved.java
- Week 5/BOJ_실버2_색종이 만들기/hyungjoon_failed.java
[색종이 만들기](https://www.acmicpc.net/problem/2630)
소요 시간 : 100분
- 방법을 도저히 모르겠어서 답지를 참고했습니다.
- 1,2,3,4 분면으로 나눠서 탐색하는 재귀함수를 구현하여 풀이를 진행했습니다. 이런 아이디어를 떠올리지를 못한거같습니다.
- 4개의 사각형으로 나눈 뒤에, 나눈 사각형을 하나씩 탐색하며, 하나라도 색종이가 다르면 다시 나누는 식으로 구현되어있습니다.
[222-풀링](https://www.acmicpc.net/problem/17829)
소요 시간 : 80분
- 분할정복이 아닌 구현으로 푼 것 같습니다.. 일단 코드리뷰 하시는데 쓰레기 코드를 제공해서 도게자 박고 시작하겠습니다 흑흑 제 힘으로 풀고 싶어서 어거지로 풀었습니다.
- 제공된 NxN 배열은 222-풀링을 한번 실행할 떄마다 N/2 x N/2 배열로 된다는 사실에 입각하여, arr를 2배씩 줄여가는 방식으로 진행했습니다.
- 한 번 줄어들 때마다 2x2 짜리 사각형을 탐색하여, 두 번째로 큰 수를 찾아냅니다.
- 여기서 굉장히 오래걸렸는데.. 11 11 9 4 이렇게 있으면 11이 나와야 하는데, 9가 나오는 건줄 알고 계속 맞왜틀 하고있었습니다.
- 이런식으로 arr의 사이즈가 1이 될 때까지 수행합니다. 최종적으로 arr엔 하나의 원소만 남게되고, 이를 출력해주면 답입니다.
- 분할정복으로 푸는 방법은 Optimized로 다시 풀어봤습니다.
672ms가 분할정복 풀이고, 852ms가 구현 풀이입니다.
분할정복이 알고리즘이라 그런지 더 빠르고 코드 가독성이나 내용도 훨씬 좋았습니다. …
> [Failed] BOJ_실버2_색종이 만들기, [Solved] BOJ_실버2_222-풀링

- Week 5/BOJ_실버2_222-풀링/Jongmin_solved.java
- Week 5/BOJ_실버2_색종이 만들기/Jongmin_solved(queue).java
- Week 5/BOJ_실버2_색종이 만들기/Jongmin_solved.java
- Week 5/BOJ_실버2_투에-모스 문자열/Jongmin_solved.java
[222풀링](https://www.acmicpc.net/problem/17829)
소요 시간 : 1시간  
- 색종이와 거의 비슷하게 풀었습니다.
- 탈출 조건이 $2 \times 2$  인 경우인 것만 다르고 부모의 1/4을 복사하는 부분은 같습니다. 
- 풀이 시간이 아슬아슬하게 800mm 정도 나오는데 아슬아슬하게 통과하는 것 같아서 메모리를 복사하는 부분을 개선해야 할 것 같습니다.
[색종이 만들기](https://www.acmicpc.net/problem/2630)
소요 시간 : 2시간  
- 재귀호출을 통해 분할정복 방식으로 구현했습니다.
- 처음에 모두 흰색인지 푸른 색인지 확인 한 후 맞으면 카운트 아니면 분할 후 재귀호출합니다.
- 최악의 경우 모든 리스트가 한개만큼 쪼개질 때까지 계속 읽어들이므로 시간 복잡도는 $O(N^2)\times O(logN)$ 인 것 같습니다. 
- 어떻게 풀지 고민하다 클래스로 만들고 관련된 메서드를 포함하면 구현할 수 있을 것 같아서 매트릭스라는 클래스 안에  isAllBlue, isAllWhite, getSubMatrix를 만들었습니다.
혹시 0, 1밖에 없어서 bit 연산자로 푸신분? 저는 해보려다가 관련된 연산자를 하나도 몰라서 포기했습니다.
> [Solved] BOJ_실버2_색종이 만들기 [Solved] BOJ_실버2_222-풀링 [Solved] BOJ_실버2_투에-모스 문자열

- Week 4/PRG_레벨2_H-Index/sohyeon.java
[H-index](https://school.programmers.co.kr/learn/courses/30/lessons/42747)
소요 시간 : 10분  
- int 배열 정렬은 오름차순으로 했지만 비교는 뒤에서부터 했기 때문에 조건을 만족하는 숫자가 나오자마자 답으로 인정하게 했습니다. 
- 주석으로 코드 설명 달아놨습니다!
> [Solved] PRG_레벨2_H-index

- Week 5/BOJ_실버2_색종이 만들기/sohyeon_failed_solution.java
[색종이 만들기](https://www.acmicpc.net/problem/2630)
pr 쓰는 중이요.......
> [Failed] PRG_실버2_색종이 만들기

- Week 5/BOJ_실버2_222-풀링/hyungjoon_failed.java
- Week 5/BOJ_실버2_222-풀링/hyungjoon_optimized.java
- Week 5/BOJ_실버2_222-풀링/hyungjoon_solved.java
- Week 5/BOJ_실버2_색종이 만들기/hyungjoon_failed.java
- Week 5/BOJ_실버2_투에-모스 문자열/hyungjoon_failed.java
[투에-모스 문자열](https://www.acmicpc.net/problem/18222)
소요 시간 : 44분
- 짝수일때 나누는것까진 접근했는데.. 마지막에 1 - f(k/2)를 못구해서 검색을 했습니다.
- 마지막에 홀수면 1 - f(k/2); 해야되는게 도저히 이해가 안가서..ㅠㅠ 이해 되신분 계시면 설명좀 부탁드립니다..
> [Failed] BOJ_실버2_투에-모스 문자열

- Week 5/BOJ_실버1_쿼드트리/Jongmin_solved.java
- Week 5/BOJ_실버2_222-풀링/Jongmin_solved.java
- Week 5/BOJ_실버2_색종이 만들기/Jongmin_solved(queue).java
- Week 5/BOJ_실버2_색종이 만들기/Jongmin_solved.java
- Week 5/BOJ_실버2_투에-모스 문자열/Jongmin_solved.java
[쿼드 트리](https://www.acmicpc.net/problem/1992)
소요 시간 : 1시간  
- 색종이와 완전히 똑같은 방식으로 풀었습니다.
- 그럼에도 시간이 오래 걸린 이유는 입력값을 색종이처럼 한 줄에 데이터 하나당 빈 공간이 있는 걸로 착각하고 엉뚱하게 처리해서 많이 방황했습니다.
- 그리고 각 4분면의 방향을 잘못 설정해서 데이터가 결과가 엉뚱하게 나와서 또 방황했습니다.
> [Solved] BOJ_실버1_쿼드 트리

- Week 5/BOJ_실버1_쿼드트리/hyungjoon_failed.py
[쿼드트리](https://www.acmicpc.net/problem/1992)
소요 시간 : 44분  
- 문제 자체를 이해하는게 시간이 너무 오래걸렸습니다. 이부분이 도저히 모르겠어서 검색을 했습니다.
- 검색하고나서는 그냥 색종이 만들기와 매우 유사한 문제였기에, 바로 풀 수 있었습니다.
- 백준 너무 불친절한듯 ㅂㄷㅂㄷ
> [Failed] BOJ_실버1_쿼드트리

- Week 5/PRG_레벨2_쿼드 압축 후 개수 세기/Jongmin_solved(stack).java
- Week 5/PRG_레벨2_쿼드 압축 후 개수 세기/Jongmin_solved.java
[쿼드 압축 후 개수 세기](https://school.programmers.co.kr/learn/courses/30/lessons/68936)
소요 시간 : 30분  
- 앞에서 진행한 쿼드 압축,색종이 문제와 거의 동일한 방식입니다.
- 차이는 0과 1의 개수를 세는 것이라서 풀이는 결국 색종이와 완전히 같은 것 같습니다.
- 분할정복과 큐를 활용해 풀어보았습니다. 
- 복습하는 느낌이었지만 별개로 코드가 이전과 별 차이가 없고 더 좋은 방향으로 가지 못한 것 같아서 아쉽네요.
> [Solved] PRG_레벨2_쿼드 압축 후 개수 세기

- Week 4/PRG_레벨2_광물 캐기/sohyeon.java
[광물캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
소요 시간 : 2일 - ing  
- 이게...... 정렬문제인가요?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ.............
- 그리디 해결법으로 틀어서 해설 보고 풀려고 합니다 -> 추가 커밋 있을 예정
- [보고 있는 해설집1](https://velog.io/@qodlstjd12/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EA%B4%91%EB%AC%BC-%EC%BA%90%EA%B8%B0-java)
- [보고 있는 해설집2](https://velog.io/@seowj0710/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-Level-2-%EA%B4%91%EB%AC%BC-%EC%BA%90%EA%B8%B0-Java)
> [Failed] PRG_레벨2_광물캐기

- Week 5/BOJ_실버2_투에-모스 문자열/sohyeon_solved.java
[투에-모스 문자열](https://www.acmicpc.net/problem/18222)
소요 시간 : 1시간  
- 어렵네요....... 
- 어려워서 답지 봤습니다.
- [확인한 답지](https://velog.io/@jh5253/%EB%B0%B1%EC%A4%80-18222-%ED%88%AC%EC%97%90-%EB%AA%A8%EC%8A%A4-%EB%AC%B8%EC%9E%90%EC%97%B4-Java%EC%9E%90%EB%B0%94)
- 늦은 밤 pr 죄송함다
- 다른 건 다 이해했는데 반복문의 범위가 64인 이유가 뭘까요.... 머리가 안돌아가요....
> [Failed] 백준_실버2_투에모스 문자열

- Week 6/LTC_Easy_Valid Parentheses/Jongmin_solved.java
[Valid Parentheses](https://leetcode.com/problems/valid-parentheses/)
소요 시간 : 10분  
- 스택을 활용해서 풀 때 알고리즘에서는 큰 어려움이 없었습니다.
- 닫히는 괄호 외에는 일단 스택에 쌓고 닫히는 괄호가 나오면 스택에서 하나 꺼내서 짝이 맞지 않은 괄호가 나오면 false 맞으면 계속 진행해서 끝까지 확인합니다.
- 중간에 닫는 괄호가 나올 때 스택이 비었는지 체크하는 부분과, 모든 문자열을 끝냈을 때 스택이 비어있는지 체크하는 부분을 미처 신경 못써서 제출 후에야 틀려서 알게 되었습니다.
> [Solved] LTC_Easy_Valid Parentheses

- Week 6/BOJ_실버3_염색체/Jongmin_solved.java
[염색체](https://www.acmicpc.net/problem/9342)
소요 시간 : 60분  
- 정규표현식을 활용하여 풀었습니다.
- 입력값에 따라 상태가 변화하는 상태패턴을 적용해 풀려고 상태 패턴 공부를 했으나 아침에 시간에 없어서 아직 적용 못했어요.
> [Solved] BOJ_실버3_염색체

- Week 6/BOJ_실버2_싸이버개강총회/Jongmin_failed.java
- Week 6/BOJ_실버3_염색체/Jongmin_solved.java
[싸이버 개강총회](https://www.acmicpc.net/problem/19583)
소요 시간 : 1시간  
- set을 이용해서 풀면 쉽겠다고 생각했는데...
- 제가 자바 Set 자료형이 어떤게 있는지 모르더라구요. 그래서 좀 찾아봤습니다.
- 또 하나 난관이 있었는데 입력이 없으면 끝내는 부분이었습니다. 
- 해당 부분은 ChatGPT의 도움을 받아 isEmpty()를 확인하면 된다고 하길래 스스로 너무 기초가 없다는 생각이 들어 열심히 해야겠다는 생각이 들었습니다.
여러분들은 문법책을 다시 보기도 하나요? 코테때 기본적인 문법은 외워놔야하는데 큰일이네요.
> [Failed] BOJ_실버2_싸이버개강총회

- Week 6/BOJ_실버2_싸이버개강총회/hyungjoon_solved.java
[싸이버개강총회](https://www.acmicpc.net/problem/19583)
소요 시간 : 52분  
- 시간을 분으로 치환해서 입장 유저와 퇴장 유저의 set에 넣은 뒤, for문을 돌면서 일치하는 값이 있으면 count++ 해줬습니다.
- 문제 자체는 쉬웠는데... while문을 시작할 때 null체크를 먼저 안하고 empty를 먼저 체크해서 NPE가 발생했습니다. 이거때문에 한참걸렸네요 ㅡ.ㅡ
> [Solved] BOJ_실버2_싸이버개강총회

- Week 6/BOJ_실버1_늑대와 올바른 단어/Jongmin_failed.java
[늑대와 올바른 단어](https://www.acmicpc.net/problem/13022)
소요 시간 : ???분  
- 스트링과 엣지케이스를 다루는데 미숙해서 며칠에 걸쳐서 조금씩 고쳤습니다.
- 결국에는 간단하게 wolf에서 w의 개수를 세고 그만큼 다른 문자들이 나오는지 체크하는 식으로 풀었습니다.
- 루프 돌 때 초기화를 잊는 경우가 있는데 꼼꼼하게 체크해서 고쳐야 할 것 같습니다.
> [Failed] BOJ_실버1_늑대와 올바른 단어

- Week 6/PRG_레벨2_모음 사전/hyungjoon_failed.java
[모음 사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
소요 시간 : 54분  
- 이전에 풀었던 문제인데, 기억이 안나서 인터넷을 참고했습니다. 왜이렇게 기억이 안나는건지 모르겠네요... ㅠㅠ
- 생각해보면 굉장히 간단한 dfs 문제인데, 아이디어 싸움이 좀 큰 것 같습니다.
- 현재 단어와 길이를 dfs 함수로 전달해주고, 길이가 5가 될 때까지 현재 단어 + 다음 단어 를 더해줍니다.
- 이후, 길이가 5가 되면 return 해줘서 다음 for문을 실행시키는 방식입니다.
> [Failed] PRG_레벨2_모음 사전

- Week 6/PRG_레벨2_모음 사전/Jongmin_failed.java
[모음 사전](https://school.programmers.co.kr/learn/courses/30/lessons/84512)
소요 시간 : ??시간  
- 문자열을 하나하나씩 조합해서 정렬을 해서 몇 번째인지 나타내려고 했으나, 생각보다 그렇게 구현하는 게 어려워서 규칙을 찾아봤습니다.
- AAAAA -> AAAAE 는 1씩 차이나고 AAAA -> AAAE 는 6이 차이납니다 마찬가지로 계산해보면 AAAE->AAAI도 6이고 이런식으로 계산해보면 AAA->AAE 는 (AAAE - AAAA) * 5 에 AAAA - AAA = 1을 더하면 됩니다. 
- 마찬가지로 계산하면 (AE-AA)도 (AAE-AAA)*5 + 1이  되므로 앞자리 차이를 구할 수 있습니다. -> 이 값들이 코드에서는 values의 배열로 저장되어 있습니다. 
- 이제 과연 해당 문자가 몇 번째 문자인지를 계산하는 방법을 구하면
- 만약  입력이 EIOU라면 맨 앞에 'E' 를 읽을 때 (E-A)*(자릿수) 로 차이를 구합니다. 차이를 구했으니 몇 번째인지 구하려면 기준점인 "A"가 1이므로 +1을 해줘야 몇 번째인지 나옵니다.
- 그 다음 문자 'I'를 읽으면 (I-A)*(자릿수) 가 계산되는데 이 값은 (EI-EA)의 결과입니다,  E->EA 로 가는 1을 더해줘야 차이가 정확해집니다.
- 이 동작을 문자열 끝가지 해서 더하면 몇 번재 인지 나옵니다.
- 규칙은 금방 찾았는데 구현하는데 오래걸렸습니다.
> [Failed] PRG_레벨2_모음사전

- Week 8/LTC_Easy_Longest Common Prefix/hyungjoon_optimized.java
- Week 8/LTC_Easy_Longest Common Prefix/hyungjoon_solved.java
[Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)
소요 시간 : 20분
- strs의 길이가 200이라 완탐 될까말까 했었는데... 통과돼서 생각보다 싱거웠던 문제였습니다.
- 정렬을 하는 것이 핵심입니다. 정렬을 한다면 맨 앞 문자열과 맨 뒤 문자열만 비교하면 됩니다.
- 처음엔 2중 for문으로 하나씩 체크했었는데.. 풀고나서 보니까 최적화가 가능해서 최적화를 진행했는데, 유의미한 차이는 없었습니다. (optimized.java) 참고
> [Solved] LTC_Easy_Longest Common Prefix

- Week 8/LTC_Easy_Find the Index of the First Occurrence in a String/hyungjoon_optimized.java
- Week 8/LTC_Easy_Find the Index of the First Occurrence in a String/hyungjoon_solved.java
[Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string)
소요 시간 : 9분
- 슬라이딩 윈도우와 비슷한 개념으로 풀었습니다.
- 다 풀고나서 답지를 봤는데.. 진짜 깔끔한 풀이가 있어서 추가로 공유합니다..!
- 워낙 간단해서 설명할게 없을거같습니다. 그냥 subString으로 needle 비교해가다가, 일치하는 값이 있으면 index를 return 해줬습니다.
너무 쉬워서 의미없는 문제였네요.. 문제 선정 실패.. ㄱ-.. 목금 문제는 좀 괜찮을겁니다..
> [Solved] LTC_Easy_Find the Index of the First Occurrence in a String

- Week 8/LTC_Easy_Find the Index of the First Occurrence in a String/Jongmin_solved.java
[Find the Index of the First Occurrence in a String](https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string)
소요 시간 : 5분  
- 이거 반칙인거같긴한데 우선 이렇게 했습니다.
- 다음에 시간 나면 직접 구현해보도록 하겠습니다!
> [Solved] LTC_Easy_Find the Index of the First Occurence in a String

- Week 8/LTC_Easy_Find the Index of the First Occurrence in a String/Jongmin_solved.java
- Week 8/LTC_Easy_Longest Common Prefix/Jongmin_solved.java
- Week 8/PRG_레벨2_압축/Jongmin_solved.java
[압축](https://school.programmers.co.kr/learn/courses/30/lessons/17684)
소요 시간 : ??분  
- 이 문제는 문제 자체에서 명확히 하는 방법을 지시해줘서 그걸 구현하면 되는 문제인 것 같습니다.
- 2번에서 일치하는 문자열 중 가장 긴 걸 먼저 찾는게 관건이었는데, 저는 사전에서 가장 긴 단어의 길이를 기억해놓고 해당 길이부터 1까지 하나씩 줄이면서 찾았습니다. 
- 다행히 시간 초과가 나지 않았습니다.
알고리즘 하면 할 수록 느는 것 같은데 따로 정리하거나 하시나요?
> [Solved] PRG_레벨2_압축

- Week 8/PRG_레벨2_압축/hyungjoon_failed.java
[압축](https://school.programmers.co.kr/learn/courses/30/lessons/17684)
소요 시간 : 66분
- 문자열...도 문자열인데 구현에 좀 더 가까운 문제였던 것 같습니다.
- Queue를 사용했습니다. 다음 문자열을 확인해서, map에 존재하는지 확인 후, 있으면 없을때까지 문자열을 늘려주고, 없으면 map에 추가 후, 출력 배열에 더해줍니다.
- 생각보다 간단한 문제였는데.. 자바로 푸는 방법(list -> array 변환, queue 사용법) 등을 잘 몰라서 검색을 좀 했습니다.. 아쉽네요.
- 큐를 안쓰고 풀어보려고 했는데 이것도 잘 안되서 큐로 풀었습니다.
> [Failed] 압축

- Week 8/PRG_레벨2_괄호 회전하기/hyungjoon_failed.py
- Week 8/PRG_레벨2_괄호 회전하기/hyungjoon_solved.py
[괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502#)
소요 시간 : 31분  
- 처음엔 괄호의 갯수로 접근했는데, 14번 테스트케이스가 딱 하나 걸렸습니다.
- 놀랍게도... 제가 이전에 틀렸던 문제 접근과 100% 똑같이 접근해서.. 틀렸었습니다. 과거의 제가 질문하기 탭에 올려놓았더군요..
- 따라서 스택으로 접근했습니다. 닫는 괄호가 있을 때, 마지막 인덱스의 값이 개괄호 (, {, [ 일 때만 정상적으로 pop 시켜주고, 나머지는 stack에 append해줬습니다.
- 마지막에 해당 스택이 비어있으면 올바른 괄호로 처리해줬습니다.
- $O(N^2)$ 시간복잡도인데.. N으로 푸는 방법이 있을까요?
> [Solved] 괄호 회전하기

- Week 8/LTC_Easy_Find the Index of the First Occurrence in a String/Jongmin_solved.java
- Week 8/LTC_Easy_Longest Common Prefix/Jongmin_solved.java
- Week 8/PRG_레벨2_괄호 회전하기/Jongmin_solved.java
- Week 8/PRG_레벨2_압축/Jongmin_solved.java
[괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
소요 시간 : 30분  
- 예전에 했던 괄호 짝 맞추는 문제 기억을 더듬어서 풀었습니다.
- 단지 달라진 점이라면 회전하는 부분이었는데요, 해당 부분은 자바 문자열의 substring 메서드와 스트링 concat을 활용했어요.
- 처음에 실행했을 때 13번이 틀렸다고 나와 의아했는데, 잘 생각해보니 stack 이 비어있는지 체크하는 부분이 없었어요. 
- 저번과 같은 실수였으나 이번에는 좀 더 빠르게 찾아 해결할 수 있었던 것 같아요. 계속 하다보니 비슷한 부분도 생기고 확실히 연습한 게 전혀 안한거보다 낫다는 생각이 들었습니다.
> [solved] PRG_레벨2_괄호 회전하기

- Week 9/BOJ_실버2_DFS와 BFS/hyungjoon_solved.java
[DFS와 BFS](https://www.acmicpc.net/problem/1260)
소요 시간 : 60분
- DFS/BFS 기본 문제인데.. 자바로 풀어서 굉장히 오래 걸렸습니다.
- 파이썬으로 풀면 금방인데, 그래프 문제는 자바로 풀어본적이 없어서 문법이랑 입력이랑.. 자료형이나 리스트같은 문법적인 이슈들로 오래걸렸습니다.
- 기본적인 문제라 [DFS/BFS 기본 골격](https://velog.io/@taehyeon96/3.-%EC%9D%B4%EC%BD%94%ED%85%8C-DFS-BFS-%EA%B0%9C%EC%9A%94-%EB%A9%94%EC%9D%B8-%EC%BD%94%EB%93%9C)만 알면 금방 풀 수 있는 문제인 것 같습니다. [동빈나님의 이코테](https://www.youtube.com/playlist?list=PLRx0vPvlEmdAghTr5mXQxGpHjWqSz0dgC) 책에 있는 코드라서 꽤나 유명합니다.
> [Solved] BOJ_실버2_DFS와 BFS

- Week 9/BOJ_실버2_DFS와 BFS/Jongmin_Solved.java
[DFS와 BFS](https://www.acmicpc.net/problem/1260)
소요 시간 : 60분  
- 오랜만에 백준이라 스트링 빌더와 tokenizer, BufferedReader, InputStreamReader 등을 써서 좋았던 것 같습니다.
- DFS와 BFS를 각각 stack과 queue 자료형을 활용해서 하려고 했는데  stack은 그냥 재귀호출 방식으로 스택을 대신하였습니다.
- 간선 정보를 2차원 배열을 사용하여 메모리가 초과되면 링크드리스트로 만들까 했는데 다행히 2차원 배열로도 메모리 초과가 되지 않아서 변경하지 않았습니다.
- 에디터의 도움이 없이 시간을 너무 오래 잡아먹어서 걱정입니다.
> [Solved] BOJ_실버2_DFS와BFS

- Week 9/BOJ_실버1_단지 번호 붙이기/hyungjoon_solved.java
[단지번호붙이기](https://www.acmicpc.net/problem/2667)
소요 시간 : 31분  
- dfs와 bfs 둘 다 풀어봤습니다.
- 상하좌우로 둘러보고, 집(1)이 있으면 탐색해가며 list에 넣어줍니다. 이 때, dfs/bfs 함수의 return값을 집이 몇개인지로 설정해줍니다.
- 마지막에 정렬을 해주고, 출력에 필요한 작업들을 진행해줍니다.
- 시뮬레이션과 dfs/bfs 합친 문제였습니다. 화요일 문제로 워밍업을 하고나니 크게 어려울 건 없었습니다.
- 자바는 코드가 진짜 너무 길게 뽑히네요..
> [Solved] BOJ_실버1_단지번호붙이기

- Week 9/BOJ_실버1_단지 번호 붙이기/Jongmin_solved.java
[단지번호붙이기](https://www.acmicpc.net/problem/2667)
소요 시간 : 60분
- queue를 활용해서 풀었습니다.
- 자잘한 실수를 많이 해서 시간이 꽤 오래 걸린 것 같습니다.
- 그 중 하나는 좌표값이 유효한지 확인하는 부분에서 x>=0  으로해야하는데 x>0으로 하는 바람에 결과값이 달랐습니다.
- 또다른 하나는 입력값 중간에 공백이 있는 줄 알고 StringTokenizer를 사용했는데 다 붙어서 나와서 오류가 나와서 시간을 허비했습니다.
- 문제를 잘 읽어야하는데 대충 읽는 습관이 잘못 들어버린 것 같아요.
- 전에 파이썬으로 비슷한 문제를 푼 기억이 있어서 어려움이 없을 줄 알았는데 숙달되도록 해야겠습니다.
> [Solved] BOJ_실버1_단지 번호 붙이기

- Week 9/LTC_Medium_Pacific Atlantic Water Flow/Jongmin_solved.java
[pacific atlantic water flow](https://leetcode.com/problems/pacific-atlantic-water-flow/)
소요 시간 : ???시간  
- 생각만큼 어려운 문제는 아니었던 것 같은데 집중을 하지 못해서 오래 걸렸습니다.
- 저는 매 셀마다 양쪽으로 흐르는지 체크를 했는데, 덕분에 시간이 굉장히 오래 걸렸고 다른 사람들에 비해 많이 낮은 결과를 받았네요.
- 다른 풀이법 참고해서 익혀야 할 것 같습니다.
> [Failed] LTC_Medium_Pacific Atlantic Water Flow

- Week 9/BOJ_골드5_토마토/Jongmin_failed.java
- Week 9/BOJ_골드5_토마토/Jongmin_solved.java
- Week 9/BOJ_실버1_단지 번호 붙이기/Jongmin_solved.java
[토마토](https://www.acmicpc.net/problem/7576)
소요 시간 : ??분  
- bfs로 풀었습니다.
- 익은 토마토의 상하좌우를 체크하면서 안 익고 큐에 담겨 있지 않은 것들만 큐에 추가하는 식으로 풀었습니다. 이때 카운트도 같이 넘겨줘서 익은 날짜도 함께 계산할 수 있었습니다.
- dfs, bfs는 이분주 내내 했는데도 ide 도움 없이 하기 힘들었는데, 연습을 많이 해야할 것 같다는 생각이 들었습니다.
- 좋은 문제 내주셔서 감사합니다.
> [failed] BOJ_골드5_토마토

- Week 10/PRG_레벨1_달리기 경주/hyungjoon_failed.java
- Week 10/PRG_레벨1_달리기 경주/hyungjoon_solved.java
[달리기 경주](https://school.programmers.co.kr/learn/courses/30/lessons/178871)
소요 시간 : 20분  
- 처음엔 배열로 될거같아서 해봤는데, (100,000 * 50,000 ) 시초가 났습니다.
- 그래서 맵으로 선언하고 선수 위치바꿔주고, 맵 갱신하는 식으로 풀었습니다
음..생각보다 플머 1은 너무쉽네요
다음엔 정답률이 낮은 레벨1로 고르고자 합니다. (40% 이하) 어떠신가요
> [Solved] PRG_레벨1_달리기 경주

- Week 10/PRG_레벨1_달리기 경주/Jongmin_failed.java
- Week 10/PRG_레벨1_달리기 경주/Jongmin_solved.py
- Week 10/PRG_레벨1_이웃한 칸/Jongmin_solved.java
[이웃한 칸](https://school.programmers.co.kr/learn/courses/30/lessons/250125)
소요 시간 : 10분  
- 풀이 방법까지 나와서... 
[달리기 경주](https://school.programmers.co.kr/learn/courses/30/lessons/178871?language=java)
소요 시간 :20분  
- 예전에 파이썬으로 풀었던 기억이 있어서 그때는 파이썬의 딕셔너리를 통해 해결했는데 자바는 해시맵을 거의 써본적이 없어서 활용법을 모르겠더라구요.
- 결국 그냥 for문을 통해 검색했고 당연히 시간 초과가 나왔습니다.
- 이번 기회를 빌려 형준님 코드 참고해서 살짝 배웠습니다. 자유롭게 쓸 수 있도록 노력하겠습니다.
> [failed] PRG_레벨1_달리기 경주 [sovled] PRG_레벨1_이웃한 칸

- Week 10/PRG_레벨1_바탕화면 정리/hyungjoon_solved.java
[바탕화면 정리](https://school.programmers.co.kr/learn/courses/30/lessons/161990)
소요 시간 : 20분  
- 아이디어만 찾으면 금방 풀 수 있는 문제였습니다.
- lux, luy, rdx, rdy를 계속해서 최소/최대값을 갱신해주면 모든 파일을 긁을 수 있는 최소영역이 됩니다.
- 커서가 끝나는 오른쪽은 +1씩 해줘야 했습니다. 이거때문에 한 5분 잡아먹은것같네요.
> [Solved] PRG_레벨1_바탕화면 정리

- Week 10/PRG_레벨1_개인정보 수집 유효기간/hyungjoon_solved.java
[개인정보 수집 유효기간](https://school.programmers.co.kr/learn/courses/30/lessons/150370)
소요 시간 : 37분
- 모든 날짜를 일로 치환시켜서 계산했습니다.
- split할 때 . 을 기준으로 한 split이 자꾸 안먹어서 혹시 해서 보니까 이스케이프 문자라서 이스케이프 처리를 따로 해줘야 했더라고요. 그래서 해줬으니 정상적으로 됐습니다.
- 마지막에 현재날짜랑 유효기간 검증날짜 비교하는걸 반대로 해서 쓸데없이 시간좀 잡아먹혔습니다 ㅠ
> [Solved] PRG_레벨1_개인정보 수집 유효기간

- Week 10/PRG_레벨1_바탕화면 정리/Jongmin_solved.java
[바탕화면 정리](https://school.programmers.co.kr/learn/courses/30/lessons/161990)
소요 시간 : 20분  
- 조금 더 효율적인 방법이 있는지 모르겠지만.. 일단은 매 줄 메 셀마다 검사해서 왼쪽 젤 위와 오른쪽 젤 아래 위치를 갱신해서 풀었습니다.
- 간단한 문제는 더 빨리 풀어야 하는데 자바로는 항상 시간이 많이 걸리는 것 같아서 걱정이네요.
> [Solved[ PRG_레벨1_바탕화면 정리

- Week 10/PRG_레벨2_호텔 대실/hyungjoon_solved.java
[호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
소요 시간 : 40분  
- 시작시간을 정렬하고, 예약된 시간을 돌면서 현재 사용중인 방의 종료시간을 비교했습니다.
- 정렬을 하면 끝나는 시간만 체크하면 되기 때문에, 큰 문제는 없었습니다.
- 원래는 compareTo 로 비교하려고했는데, 05:50 에서 10분 청소하면 06:00 처럼 시가 변하게 되는게 처리하는게 번거로울 것 같아서, 숫자로 변환해서 풀었습니다.
> [Solved] PRG_레벨2_호텔 대실

- Week 10/PRG_레벨2_리코쳇 로봇/hyungjoon_solved.java
[리코쳇 로봇](https://school.programmers.co.kr/learn/courses/30/lessons/169199)
소요 시간 : 50분  
- bfs인건 알았는데, 미끄러지는걸 생각을 못해서 답지를 참고했습니다.
- 핵심은 while문을 통해서, 맵 끝이나 장애물이 닿을 때까지 nr, nc를 갱신해나가는 것이었습니다.
- 그렇게 해서 도달한 곳까지의 거리가 기존에 방문했을 때 거리보다 짧다면, 거리를 짧은것으로 갱신해줍니다.
- G를 만나면 그자리에서 바로 d를 return해줍니다.
- 코테에서 자주 보였던 유형이었는데, 이번 기회에 이해가 딱 되서 너무 좋은 문제였던 것 같습니다!
> [Failed] PRG_레벨2_리코쳇 로봇

- Week 10/PRG_레벨2_호텔 대실/Jongmin_solved.java
[호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
소요 시간 : 50분  
- 처음에는 종료 시간을 기준으로 정렬하고 예약 건마다 호텔 이 준비 상태인지 확인하고 준비상태가 된 방이 없으면 추가하는 방식으로 진행했습니다.
- 테스트 통과하지 못하는 경우가 많아서 반례를 보다보니 시작 시간을 중심으로 정렬하면 나을까 싶어서 했더니 다 통과했는데
- 제대로 이해하지 못한 상태로 풀었고 시간도 많이 걸렸습니다.
> [Failed] PRG_ 레벨2_호텔 대실

- Week 10/PRG_레벨2_미로 탈출/Jongmin_solved.java
[미로 탈출](https://school.programmers.co.kr/learn/courses/30/lessons/159993)
소요 시간 : 40분  
- 레버를 들렸다가 도착지점에 가야하는 것 빼고는 일반적인 bfs 문제라고 생각됩니다.
- 레버를 들려야 하므로 S->L, L->E 두 번의 bfs 탐색을 활용하여 풀었습니다.
- 많이 푼 문제임에도 불구하고 시간이 오래걸렸는데, direction을 d[i][0], d[i][1] 로 설정했어야 했는데 d[0][0], d[0][1]; 로 해서 한 방향으로만 움직였는데 그걸 뒤늦게 발견했습니다.
> [Solved] PRG_레벨2_미로 탈출

- Week 10/PRG_레벨2_연속된 부분 수열의 합/hyungjoon_failed.java
- Week 10/PRG_레벨2_연속된 부분 수열의 합/hyungjoon_solved.java
[연속된 부분 수열의 합](https://school.programmers.co.kr/learn/courses/30/lessons/178870)
소요 시간 : 30분  
- 투포인터를 사용해서 풀었습니다.
- 처음엔 시초가 발생해서 뭔가 했는데.. 생각해보니까 더할 때마다 sum을 해줘서였습니다.
- sum을 밖으로 빼고, 그 sum을 계속해서 연산해주는 작업으로 변경하고 나니, 시초가 확 줄었습니다.
- 투포인터 문제는 l < r 기준 잡는게 참 모호한것같습니다.. 어쩔때는 l <= r이고 어쩔떄는 l < r 이런식인데 종민님은 어떻게 하시나요..?
> [Solved] PRG_레벨2_연속된 부분 수열의 합

- Week 10/PRG_레벨3_미로 탈출 명령어/Jongmin_failed.java
[미로 탈출 명령어](https://school.programmers.co.kr/learn/courses/30/lessons/150365)
소요 시간 : 120분  
- 이건 최적해가 있을 것 같아서 처음에는 (r, c), (x, y)와의 좦표 차이를 통해 기본적인 최소 루트에 k와의 차만큼 d, l, r, u 방향으로 추가하면 되겠다 싶었는데 복잡해서 그냥 dfs로 풀었습니다.
- 동서남북을 알파벳 순으로 탐색하여 깊이 우선으로 탐색하여 먼저 나오는 답이 알파벳 순으로 빠른 답이라 생각하고 바로 결과를 리턴했습니다.
- 최소 경로와 k와의 차이가 홀수가 아니면 가능한 경로가 아니기 때문에(최소경로에 상하좌우 하나를 추가할 때마다 짝으로 반대 방향을 추가해줘야 목적지에 도달할 수 있으므로) 처음에 그걸로 일단 불가능한 경로를 걸러냈습니다.
- 그리고 남은 거리(움직이는 횟수)가 현재 좌표에서 목표 지점까지의 거리보다 작으면 마찬가지로 도달할 수 없기 때문에 미리 걸러냈습니다.
- 코드가 다소 지저분해서 다음에는 깔끔하게 올릴 수 있도록 하겠습니다.!!
-
> [failed] PRG_레벨3_미로 탈출 명령어

- Week 17/PRG_레벨1_그리움 점수/hyungjoon_solved.java
[그리움 점수](https://school.programmers.co.kr/learn/courses/30/lessons/176963)
소요 시간 : 11분
- 단순한 map 문제, mapping 후 계산만 해주면 됐음
- 자바에선 map을 어떻게 확인하나.. 해서 알아봤더니 map.forEach구문이 있어서 이를 알게되었음.
> [Solved] PRG_레벨1_그리움 점수

- Week 17/PRG_레벨1_데이터 분석/Jongmin_solved.java
[데이터 분석](https://school.programmers.co.kr/learn/courses/30/lessons/250121)
소요 시간 : 15분  
- 필터와 정렬 기능이 있어서 스트림을 활용하면 쉬울 것 같은 문제였습니다.
- 그런데 자바에서 이차원 배열을 어떻게 스트림으로 만들지와, 그렇게 만든 스트림에서 정작 정렬하는 방법이 잘 생각나지 않아 검색해서 적용했습니다.
- 그러다보니 실제로 한건 해시맵과 필터밖에 없네요. 반성합니다...
- 프로젝트에서 원시 타입을 잘 안쓰다보니 막상 알고리즘에서는 전혀 활용을 하지 못하는 것 같습니다.
> [solved] PRG_레벨1_데이터 분석

- Week 17/PRG_레벨1_그리움 점수/Jongmin_failed.java
- Week 17/PRG_레벨1_데이터 분석/Jongmin_solved.java
[그리움 점수](https://school.programmers.co.kr/learn/courses/30/lessons/176963?language=java)
소요 시간 : 25분  
- 각 사람의 이름과 점수를 hashmap에 담아서 photo 배열에서 한 장씩 그리움 점수를 합산하는 방식으로 풀었습니다.
- 그냥 for문을 쓰면 더 쉬웠을 것 같은데 stream 활용법을 찾아보면서 계산했습니다.
- 크게 어려운 부분은 없었으나 스트림 활용법을 잘 몰라서 실제로 알고리즘을 풀 때는 for문으로 풀어야겠다는 다짐을 했습니다.
- 가독성도 저는 2중 반복문의 경우에는 stream이 for문에 비해서 좋은지 못 느꼈던 시간이었습니다.
- 스트림 계속 공부해서 잘 쓰는게 좋을까요?
> [Failed] PRG_레벨1_그리움점수

- Week 17/PRG_레벨1_문자열 나누기/Jongmin_Solved.java
[문자열 나누기](https://school.programmers.co.kr/learn/courses/30/lessons/140108)
소요 시간 : 15분  
- count라는 변수를 두어 첫 문자와 같은 문자가 나오면 하나씩 더해가고 다른 문자가 나오면 하나씩 빼는 방식으로 풀었습니다.
- 첫 문자를 읽어들일 때 count가 0이면 answer를 1씩 중가하면서 문자열의 갯수를 측정했습니다.
- 만약 문자열의 개수가 아니라 문자열들을 분리해서 문자열을을 넘기는 방식이었다면 문자열을 하나씩 읽어들여 별도로 문자를 저장하고 count가 0이 됐을 때 저장한 문자들을 문자열로 변환하여 List<String>에 추가하는 방식으로 했을 것 같습니다.
-
> [Solved] PRG_레벨1_문자열 나누기

- Week 17/PRG_레벨1_석유 시추/hyungjoon_failed.java
- Week 17/PRG_레벨1_석유 시추/hyungjoon_solved.java
[석유 시추](https://school.programmers.co.kr/learn/courses/30/lessons/250136)
소요 시간 : 45분  
- 처음엔 모든 (i, j)에서 dfs를 수행했고, 정확도는 모두 통과했으나 효율성에서 막혔습니다.
- 답지를 봤는데.. 모든 열별로 석유가 얼마나 매장되어있는지 확인하면 된다는데.. 솔직히 잘 이해가 가지 않습니다. 별도로 다시 복습해야할것같아요...
- [해당링크](https://nahwasa.com/entry/%EC%9E%90%EB%B0%94-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%84%9D%EC%9C%A0-%EC%8B%9C%EC%B6%94-PCCP-%EA%B8%B0%EC%B6%9C%EB%AC%B8%EC%A0%9C-2%EB%B2%88-Lv2-Java)에선 bfs로 풀었고, set을 활용하던데... 엄.. 잘 모르겠네요 내일 다시 복습하도록 하겠습니다
> [Failed] PRG_레벨2_석유 시추
